"""initial_schema

Revision ID: 9432948b6aba
Revises: 
Create Date: 2026-10-09 01:28:01.973319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9432948b6aba'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concurrency_limit_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(), nullable=False),
    sa.Column('target_id', sa.String(), nullable=False),
    sa.Column('max_concurrency', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("target_type IN ('WORKFLOW', 'TASK_TYPE')", name='ck_concurrency_policies_target_type'),
    sa.CheckConstraint('max_concurrency >= 1', name='ck_concurrency_policies_max_concurrency'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('target_type', 'target_id', name='uq_concurrency_policies_target')
    )
    op.create_index(op.f('ix_concurrency_limit_policies_id'), 'concurrency_limit_policies', ['id'], unique=False)
    op.create_index(op.f('ix_concurrency_limit_policies_target_id'), 'concurrency_limit_policies', ['target_id'], unique=False)
    op.create_index(op.f('ix_concurrency_limit_policies_target_type'), 'concurrency_limit_policies', ['target_type'], unique=False)
    op.create_table('job_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_definitions_category'), 'job_definitions', ['category'], unique=False)
    op.create_index(op.f('ix_job_definitions_id'), 'job_definitions', ['id'], unique=False)
    op.create_index(op.f('ix_job_definitions_name'), 'job_definitions', ['name'], unique=False)
    op.create_table('rate_limit_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(), nullable=False),
    sa.Column('target_id', sa.String(), nullable=False),
    sa.Column('max_requests', sa.Integer(), nullable=False),
    sa.Column('window_seconds', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("target_type IN ('CATEGORY', 'JOB_CATEGORY', 'TASK_TYPE', 'WORKFLOW')", name='ck_rate_limit_policies_target_type'),
    sa.CheckConstraint('max_requests >= 1', name='ck_rate_limit_policies_max_requests'),
    sa.CheckConstraint('window_seconds >= 1', name='ck_rate_limit_policies_window_seconds'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('target_type', 'target_id', name='uq_rate_limit_policies_target')
    )
    op.create_index(op.f('ix_rate_limit_policies_id'), 'rate_limit_policies', ['id'], unique=False)
    op.create_index(op.f('ix_rate_limit_policies_target_id'), 'rate_limit_policies', ['target_id'], unique=False)
    op.create_index(op.f('ix_rate_limit_policies_target_type'), 'rate_limit_policies', ['target_type'], unique=False)
    op.create_table('schedule_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('schedule_type', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_definitions_id'), 'schedule_definitions', ['id'], unique=False)
    op.create_index(op.f('ix_schedule_definitions_name'), 'schedule_definitions', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('admin', 'operator', 'observer')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('workers',
    sa.Column('worker_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('worker_id')
    )
    op.create_table('workflow_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_definitions_id'), 'workflow_definitions', ['id'], unique=False)
    op.create_index(op.f('ix_workflow_definitions_name'), 'workflow_definitions', ['name'], unique=False)
    op.create_table('schedule_occurrences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_definition_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['schedule_definition_id'], ['schedule_definitions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schedule_definition_id', 'scheduled_for', name='uq_schedule_occurrences_def_scheduled_for')
    )
    op.create_index(op.f('ix_schedule_occurrences_id'), 'schedule_occurrences', ['id'], unique=False)
    op.create_index(op.f('ix_schedule_occurrences_schedule_definition_id'), 'schedule_occurrences', ['schedule_definition_id'], unique=False)
    op.create_index(op.f('ix_schedule_occurrences_scheduled_for'), 'schedule_occurrences', ['scheduled_for'], unique=False)
    op.create_index(op.f('ix_schedule_occurrences_status'), 'schedule_occurrences', ['status'], unique=False)
    op.create_table('workflow_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('triggered_by', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_summary', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELLED')", name='ck_workflow_runs_status'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_runs_id'), 'workflow_runs', ['id'], unique=False)
    op.create_index(op.f('ix_workflow_runs_status'), 'workflow_runs', ['status'], unique=False)
    op.create_index(op.f('ix_workflow_runs_workflow_id'), 'workflow_runs', ['workflow_id'], unique=False)
    op.create_table('workflow_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('task_type', sa.String(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_id', 'name', name='uq_workflow_tasks_workflow_name')
    )
    op.create_index(op.f('ix_workflow_tasks_id'), 'workflow_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_workflow_tasks_name'), 'workflow_tasks', ['name'], unique=False)
    op.create_index(op.f('ix_workflow_tasks_workflow_id'), 'workflow_tasks', ['workflow_id'], unique=False)
    op.create_table('executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_definition_id', sa.Integer(), nullable=True),
    sa.Column('schedule_occurrence_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=True),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.String(), nullable=True),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_summary', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['job_definition_id'], ['job_definitions.id'], ),
    sa.ForeignKeyConstraint(['schedule_occurrence_id'], ['schedule_occurrences.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schedule_occurrence_id', name='uq_executions_schedule_occurrence_id')
    )
    op.create_index(op.f('ix_executions_category'), 'executions', ['category'], unique=False)
    op.create_index(op.f('ix_executions_id'), 'executions', ['id'], unique=False)
    op.create_index(op.f('ix_executions_priority'), 'executions', ['priority'], unique=False)
    op.create_index(op.f('ix_executions_schedule_occurrence_id'), 'executions', ['schedule_occurrence_id'], unique=False)
    op.create_index(op.f('ix_executions_status'), 'executions', ['status'], unique=False)
    op.create_table('workflow_edges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('upstream_task_id', sa.Integer(), nullable=False),
    sa.Column('downstream_task_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('upstream_task_id != downstream_task_id', name='ck_workflow_edges_no_self_dependency'),
    sa.ForeignKeyConstraint(['downstream_task_id'], ['workflow_tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['upstream_task_id'], ['workflow_tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_id', 'upstream_task_id', 'downstream_task_id', name='uq_workflow_edges_workflow_upstream_downstream')
    )
    op.create_index(op.f('ix_workflow_edges_downstream_task_id'), 'workflow_edges', ['downstream_task_id'], unique=False)
    op.create_index(op.f('ix_workflow_edges_id'), 'workflow_edges', ['id'], unique=False)
    op.create_index(op.f('ix_workflow_edges_upstream_task_id'), 'workflow_edges', ['upstream_task_id'], unique=False)
    op.create_index(op.f('ix_workflow_edges_workflow_id'), 'workflow_edges', ['workflow_id'], unique=False)
    op.create_table('rate_limit_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('execution_id', sa.Integer(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['policy_id'], ['rate_limit_policies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rate_limit_records_execution_id'), 'rate_limit_records', ['execution_id'], unique=False)
    op.create_index(op.f('ix_rate_limit_records_id'), 'rate_limit_records', ['id'], unique=False)
    op.create_index(op.f('ix_rate_limit_records_policy_id'), 'rate_limit_records', ['policy_id'], unique=False)
    op.create_index(op.f('ix_rate_limit_records_recorded_at'), 'rate_limit_records', ['recorded_at'], unique=False)
    op.create_table('workflow_task_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_run_id', sa.Integer(), nullable=False),
    sa.Column('workflow_task_id', sa.Integer(), nullable=False),
    sa.Column('execution_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_summary', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('PENDING', 'READY', 'RUNNING', 'SUCCEEDED', 'FAILED', 'SKIPPED', 'CANCELLED')", name='ck_workflow_task_executions_status'),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_task_id'], ['workflow_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('execution_id', name='uq_workflow_task_executions_execution_id'),
    sa.UniqueConstraint('workflow_run_id', 'workflow_task_id', name='uq_workflow_task_executions_run_task')
    )
    op.create_index(op.f('ix_workflow_task_executions_execution_id'), 'workflow_task_executions', ['execution_id'], unique=False)
    op.create_index(op.f('ix_workflow_task_executions_id'), 'workflow_task_executions', ['id'], unique=False)
    op.create_index(op.f('ix_workflow_task_executions_status'), 'workflow_task_executions', ['status'], unique=False)
    op.create_index(op.f('ix_workflow_task_executions_workflow_run_id'), 'workflow_task_executions', ['workflow_run_id'], unique=False)
    op.create_index(op.f('ix_workflow_task_executions_workflow_task_id'), 'workflow_task_executions', ['workflow_task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_task_executions_workflow_task_id'), table_name='workflow_task_executions', if_exists=True)
    op.drop_index(op.f('ix_workflow_task_executions_workflow_run_id'), table_name='workflow_task_executions', if_exists=True)
    op.drop_index(op.f('ix_workflow_task_executions_status'), table_name='workflow_task_executions', if_exists=True)
    op.drop_index(op.f('ix_workflow_task_executions_id'), table_name='workflow_task_executions', if_exists=True)
    op.drop_index(op.f('ix_workflow_task_executions_execution_id'), table_name='workflow_task_executions', if_exists=True)
    op.drop_table('workflow_task_executions', if_exists=True)
    op.drop_index(op.f('ix_rate_limit_records_recorded_at'), table_name='rate_limit_records', if_exists=True)
    op.drop_index(op.f('ix_rate_limit_records_policy_id'), table_name='rate_limit_records', if_exists=True)
    op.drop_index(op.f('ix_rate_limit_records_id'), table_name='rate_limit_records', if_exists=True)
    op.drop_index(op.f('ix_rate_limit_records_execution_id'), table_name='rate_limit_records', if_exists=True)
    op.drop_table('rate_limit_records', if_exists=True)
    op.drop_index(op.f('ix_workflow_edges_workflow_id'), table_name='workflow_edges', if_exists=True)
    op.drop_index(op.f('ix_workflow_edges_upstream_task_id'), table_name='workflow_edges', if_exists=True)
    op.drop_index(op.f('ix_workflow_edges_id'), table_name='workflow_edges', if_exists=True)
    op.drop_index(op.f('ix_workflow_edges_downstream_task_id'), table_name='workflow_edges', if_exists=True)
    op.drop_table('workflow_edges', if_exists=True)
    op.drop_index(op.f('ix_executions_status'), table_name='executions', if_exists=True)
    op.drop_index(op.f('ix_executions_schedule_occurrence_id'), table_name='executions', if_exists=True)
    op.drop_index(op.f('ix_executions_priority'), table_name='executions', if_exists=True)
    op.drop_index(op.f('ix_executions_id'), table_name='executions', if_exists=True)
    op.drop_index(op.f('ix_executions_category'), table_name='executions', if_exists=True)
    op.drop_table('executions', if_exists=True)
    op.drop_index(op.f('ix_workflow_tasks_workflow_id'), table_name='workflow_tasks', if_exists=True)
    op.drop_index(op.f('ix_workflow_tasks_name'), table_name='workflow_tasks', if_exists=True)
    op.drop_index(op.f('ix_workflow_tasks_id'), table_name='workflow_tasks', if_exists=True)
    op.drop_table('workflow_tasks', if_exists=True)
    op.drop_index(op.f('ix_workflow_runs_workflow_id'), table_name='workflow_runs', if_exists=True)
    op.drop_index(op.f('ix_workflow_runs_status'), table_name='workflow_runs', if_exists=True)
    op.drop_index(op.f('ix_workflow_runs_id'), table_name='workflow_runs', if_exists=True)
    op.drop_table('workflow_runs', if_exists=True)
    op.drop_index(op.f('ix_schedule_occurrences_status'), table_name='schedule_occurrences', if_exists=True)
    op.drop_index(op.f('ix_schedule_occurrences_scheduled_for'), table_name='schedule_occurrences', if_exists=True)
    op.drop_index(op.f('ix_schedule_occurrences_schedule_definition_id'), table_name='schedule_occurrences', if_exists=True)
    op.drop_index(op.f('ix_schedule_occurrences_id'), table_name='schedule_occurrences', if_exists=True)
    op.drop_table('schedule_occurrences', if_exists=True)
    op.drop_index(op.f('ix_workflow_definitions_name'), table_name='workflow_definitions', if_exists=True)
    op.drop_index(op.f('ix_workflow_definitions_id'), table_name='workflow_definitions', if_exists=True)
    op.drop_table('workflow_definitions', if_exists=True)
    op.drop_table('workers', if_exists=True)
    op.drop_index(op.f('ix_users_username'), table_name='users', if_exists=True)
    op.drop_index(op.f('ix_users_id'), table_name='users', if_exists=True)
    op.drop_index(op.f('ix_users_email'), table_name='users', if_exists=True)
    op.drop_table('users', if_exists=True)
    op.drop_index(op.f('ix_schedule_definitions_name'), table_name='schedule_definitions', if_exists=True)
    op.drop_index(op.f('ix_schedule_definitions_id'), table_name='schedule_definitions', if_exists=True)
    op.drop_table('schedule_definitions', if_exists=True)
    op.drop_index(op.f('ix_rate_limit_policies_target_type'), table_name='rate_limit_policies', if_exists=True)
    op.drop_index(op.f('ix_rate_limit_policies_target_id'), table_name='rate_limit_policies', if_exists=True)
    op.drop_index(op.f('ix_rate_limit_policies_id'), table_name='rate_limit_policies', if_exists=True)
    op.drop_table('rate_limit_policies', if_exists=True)
    op.drop_index(op.f('ix_job_definitions_name'), table_name='job_definitions', if_exists=True)
    op.drop_index(op.f('ix_job_definitions_id'), table_name='job_definitions', if_exists=True)
    op.drop_index(op.f('ix_job_definitions_category'), table_name='job_definitions', if_exists=True)
    op.drop_table('job_definitions', if_exists=True)
    op.drop_index(op.f('ix_concurrency_limit_policies_target_type'), table_name='concurrency_limit_policies', if_exists=True)
    op.drop_index(op.f('ix_concurrency_limit_policies_target_id'), table_name='concurrency_limit_policies', if_exists=True)
    op.drop_index(op.f('ix_concurrency_limit_policies_id'), table_name='concurrency_limit_policies', if_exists=True)
    op.drop_table('concurrency_limit_policies', if_exists=True)
    # ### end Alembic commands ###
